### ISSUE TITLE
Feature request: ability to import and export the glossary

### ISSUE THREAD

**Issue by runasand** [transifex/transifex-old-core#41]
I would like to be able to import and export the glossary for my project so that I can work on / store it in my Git repository.

**Comment by xantippe** [comment]
Hi,
I found only a button "Download" but I dont find "Upload"..?? how ca I find this?

Thanks

**Comment by dimoschi** [comment]
Please use our [contact form](www.transifex.com/contact/) to contact with Transifex Support.

**Comment by xantippe** [comment]
```https://github.com/transifex/transifex/issues/www.transifex.com/contact/```

=> response: 404 Error :-(
